version: '3.9'

services:

  postgres:
    container_name: movies
    image: postgres
    restart: always
    shm_size: 128mb
    # volumes:
    #   - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: movies
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: postgres_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: herick@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"