FROM node:alpine AS build

WORKDIR /application

COPY . .

RUN npm i --quiet --no-optional --no-fund --loglevel=error && \
    npm run build \
    npm run migration:run

EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]
